name = "auth0-mcp-integration"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# KV namespace configuration
kv_namespaces = [
  { binding = "AUTH_STORE", id = "YOUR_KV_NAMESPACE_ID", preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" }
]

# Environment variables
[vars]
NODE_ENV = "production"

# Secret variables (these are placeholders, use wrangler secret to set them)
# wrangler secret put AUTH0_DOMAIN
# wrangler secret put AUTH0_CLIENT_ID
# wrangler secret put AUTH0_CLIENT_SECRET
# wrangler secret put AUTH0_CALLBACK_URL
# wrangler secret put SALT

[site]
bucket = "./public"

[env.development]
name = "auth0-mcp-integration-dev"
vars = { NODE_ENV = "development" } 